# Generated by Django 3.2.7 on 2022-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220926_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image1',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image2',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image3',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
